title: Sohesh's blog
remote_theme: chesterhow/tale
github:
  is_project_page: false
  is_user_page: true
  owner_name: Sohesh
  owner_url: https://soheshts.github.io/
  owner_gravatar_url: https://soheshts.github.io/images/me.jpg
